{% set version = "0.16.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fabricatr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fabricatr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fabricatr/fabricatr_{{ version }}.tar.gz
  sha256: ffe705a7167e8f356dd76c135d2f8f6c28dbdfff3c63cea432f36c4627483739

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-backports
    - r-rlang >=0.2.0
    - r-tibble
  run:
    - r-base
    - r-backports
    - r-rlang >=0.2.0
    - r-tibble

test:
  commands:
    - $R -e "library('fabricatr')"           # [not win]
    - "\"%R%\" -e \"library('fabricatr')\""  # [win]

about:
  home: https://declaredesign.org/r/fabricatr, https://github.com/DeclareDesign/fabricatr
  license: MIT
  summary: Helps you imagine your data before you collect it. Hierarchical data structures and correlated data can be easily simulated, either from random number generators or by resampling from existing data sources. This package is faster with 'data.table' and 'mvnfast' installed.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: fabricatr
# Type: Package
# Title: Imagine Your Data Before You Collect It
# Version: 0.12.0
# Authors@R: c(person("Graeme", "Blair", email = "graeme.blair@ucla.edu", role = c("aut", "cre")), person("Jasper", "Cooper", email = "jjc2247@columbia.edu", role = c("aut")), person("Alexander", "Coppock", email = "alex.coppock@yale.edu", role = c("aut")), person("Macartan", "Humphreys", email = "macartan@gmail.com", role = c("aut")), person("Aaron", "Rudkin", email = "rudkin@ucla.edu", role = c("aut")), person("Neal", "Fultz", email = "nfultz@gmail.com", role = c("aut")))
# Description: Helps you imagine your data before you collect it. Hierarchical data structures and correlated data can be easily simulated, either from random number generators or by resampling from existing data sources. This package is faster with 'data.table' and 'mvnfast' installed.
# URL: https://declaredesign.org/r/fabricatr, https://github.com/DeclareDesign/fabricatr
# BugReports: https://github.com/DeclareDesign/fabricatr/issues
# Depends: R (>= 3.5.0)
# Imports: rlang (>= 0.2.0), tibble, backports
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# Suggests: testthat, data.table, mvnfast, MASS, extraDistr
# NeedsCompilation: no
# Packaged: 2021-01-09 00:36:57 UTC; ac2595
# Author: Graeme Blair [aut, cre], Jasper Cooper [aut], Alexander Coppock [aut], Macartan Humphreys [aut], Aaron Rudkin [aut], Neal Fultz [aut]
# Maintainer: Graeme Blair <graeme.blair@ucla.edu>
# Repository: CRAN
# Date/Publication: 2021-01-09 07:30:02 UTC
