{% set version = '0.8.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fabricatr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fabricatr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fabricatr/fabricatr_{{ version }}.tar.gz
  sha256: 7de478ed5e255fc6c53c94f55eb499553bd9f417a43712925de599470419a5d3

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rlang >=0.2.0
  run:
    - r-base
    - r-rlang >=0.2.0

test:
  commands:
    - $R -e "library('fabricatr')"           # [not win]
    - "\"%R%\" -e \"library('fabricatr')\""  # [win]

about:
  home: https://declaredesign.org/r/fabricatr, https://github.com/DeclareDesign/fabricatr
  license: MIT
  summary: Helps you imagine your data before you collect it. Hierarchical data structures and
    correlated data can be easily simulated, either from random number generators or
    by resampling from existing data sources. This package is faster with 'data.table'
    and 'mvnfast' installed.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: fabricatr
# Type: Package
# Title: Imagine Your Data Before You Collect It
# Version: 0.8.0
# Authors@R: c(person("Graeme", "Blair", email = "graeme.blair@ucla.edu", role = c("aut", "cre")), person("Jasper", "Cooper", email = "jjc2247@columbia.edu", role = c("aut")), person("Alexander", "Coppock", email = "alex.coppock@yale.edu", role = c("aut")), person("Macartan", "Humphreys", email = "macartan@gmail.com", role = c("aut")), person("Aaron", "Rudkin", email = "rudkin@ucla.edu", role = c("aut")), person("Neal", "Fultz", email = "nfultz@gmail.com", role = c("aut")))
# Description: Helps you imagine your data before you collect it. Hierarchical data structures and correlated data can be easily simulated, either from random number generators or by resampling from existing data sources. This package is faster with 'data.table' and 'mvnfast' installed.
# URL: https://declaredesign.org/r/fabricatr, https://github.com/DeclareDesign/fabricatr
# BugReports: https://github.com/DeclareDesign/fabricatr/issues
# Depends: R (>= 3.4.0)
# Imports: rlang (>= 0.2.0)
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# Suggests: testthat, data.table, mvnfast, MASS
# NeedsCompilation: no
# Packaged: 2019-03-12 00:43:35 UTC; gdblair
# Author: Graeme Blair [aut, cre], Jasper Cooper [aut], Alexander Coppock [aut], Macartan Humphreys [aut], Aaron Rudkin [aut], Neal Fultz [aut]
# Maintainer: Graeme Blair <graeme.blair@ucla.edu>
# Repository: CRAN
# Date/Publication: 2019-03-12 06:02:50 UTC
