travis:
  secure:
    BINSTAR_TOKEN: BP+nRJFlHYuVYCc/csyZKXZQCkwXkGPpRCz6q/zQP4kX2HuYQNXBl13GNvx6c1KZqWUPjAza5RsqgMn14HkVXL0NoTVsNezAESl+/odA7HCPmz9sUM7XLvu/3D5B7yWeyA7uo0teuswkpBnqufmeZbHrvcOjchpAXdLMULQRRBoy969ff3R/U62ZMnA53FbxjNnzte+bKFi7jY6nQNivJjBfYN8HXEmm4KEg9JkUPLkTY/NdOaIdShCRb2+X9hvS4rmUmKUwqrbJliWISQzdipI4vCVX5PTWlpd5rnj3PUs23RyTdP0AbQz45ZdeEJMNsnx/E54cTQEDxC1ASaBJW4b/Ku5cF/NvyiHFZO2eceiehd/t/MJtNPAFEyhqlrEJJRNJv3VxyE54YoPQVkOrkcRQIQ2cZaVkrpqbxCwxhLE5wJdvJzN+xUO0kvdz1y3kDvj3X1ir22RNuEMULV9JO4dBm5XzJiUAbHiKZCV9cEzzZySkjY1Gj9Db/QUV+WpXoUPRnY+LZDM83fvq9tvVOJ5vnn35bus364WkZJPUABfvnLyIYrM4O0krc6DYNrOdqh8TSwjdgDy1SAhZvJBdgPh3VLiU4VGAYkNr+0DtUMHB2B5awg+8qhAbLVn9sQ4fJfbU1VnRMm4t8V/B3KdsFz1Dj5Q5/pEVBc+LXJ1Bkk0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
