appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: F5vTIadSqzm9gC06hDuvPqW626NYA4e4IgwF804smCmTWzEc6RmHgOy2eFTR7v8sD/xxuXBXMf2sVJHPezimCtEPW8678StXa4jKbBGbur0n0vAYU+aGMLGhWp4+ZIY2heR+Z1tB9FtTyEe37m5tl4mnKbuiiHFDjidE2W+m7SZ0eKgtGdfIQMYyYehP0/p0OgUdPmmaeb9bPLHbnAGCg1tvFo3fBJqcugtitwcLKNREqc3iG9yn+HwjQ5bxVZR1x69A1r/ViJQL84DyiHNDSMkBZTykxLmhSVW2LoR8PpaWKe07Dc3avRsM4VhfSsqDh+/hJGamolQx6vuliQOqWewHrUeLoznH2T3u2pWadUX33xBiC5oyenBgkLxA87GwTvuVad1efF4eXc6eOSm8GywrZL7FAjyM9uMJY+Stnzn6xUrF6K2QgXcktH0DMftc4uUvmB+9EKtf3z+LkZYa9yZxzkeofYC2RfrDDYaHI6y3a1GJzYVayNyN4MD1QzZZwMMj6zLTj9GsLRDyWEMhbtbmx6MSxACfe4fMZft1xJc0Zw0b3xsrAIOEWSTxFWmOXHT80h41Xth78gKsVVyqxTcz3D9C15OLo47ugzWXPBwb7MkHOzYkJVWbxZzlkJi4oHm/nmu8dnMcW/MIYAw3NQLnDjRV6XVxQYU9QDxtRlU=}
